### ISSUE TITLE
test_deploy

### ISSUE THREAD

**Issue by churik** [churik/ProdTest#1]
test_deploy

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0xcd06eaa4f7d10d4a1c1cf1385c8e72cc81bce081](https://etherscan.io/address/0xcd06eaa4f7d10d4a1c1cf1385c8e72cc81bce081)
![QR Code](https://openbounty.status.im/qr/churik/ProdTest/bounty/1/a61ab27dcb4fd251aa589f5207fc4af561aaeed3b62030addefbbbb25eb3ab93/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
